### ISSUE TITLE
program doesn't exit correctly

### ISSUE THREAD

**Issue by gawdsed** [PsiLupan/MakeLobbiesGreatAgain#10] opened 2016-12-14 02:54 UTC
Once program is exited, java/the app runs in the background and is not terminated correctly. Killing java will then kill the program correctly.

**Comment by PsiLupan** [comment] 2016-12-14 03:08
Can reproduce.

It's caused by Exit being simply a System.exit() call, and I think PCap4J may need to properly cleanup the device. Will look into it further soon.

**Comment by PsiLupan** [comment] 2016-12-14 03:31
Fixed with https://github.com/PsiLupan/MakeLobbiesGreatAgain/commit/e0d0610d9e7a224fc657e4b981066977e8f6523c

It looks like the shutdown thread, which wasn't having the intended effect in the first place, was somehow hanging. It's been removed, rather than attempting to diagnose it due to it not working anyways.

**Closed by PsiLupan** 2016-12-14 03:31 UTC
Labels: bug
